## Вычисления с помощью Numpy

In [2]:
'''Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, 
то есть состоящий из 5 строк и 2 столбцов. Первый 
столбец должен содержать числа 1, 2, 3, 3, 1, а 
второй - числа 6, 8, 11, 10, 7. Будем считать, что 
каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, 
используя метод mean массива Numpy. Результат запишите
в массив mean_a, в нем должно быть 2 элемента.
''';

In [3]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [5]:
# Для получения 5*2 просто транспонируем матрицу
a = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
print("Средние значения столбцов: {}".format(a.mean(axis=0)))

Средние значения столбцов: [2.  8.4]


In [7]:
mean_a = np.array([2, 8.4])
mean_a

array([2. , 8.4])

In [8]:
'''Задание 2
Вычислите массив a_centered, отняв от значений 
массива “а” средние значения соответствующих 
признаков, содержащиеся в массиве mean_a. Вычисление 
должно производиться в одно действие. Получившийся 
массив должен иметь размер 5x2.
''';

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [10]:
# Более правильное решение;
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [11]:
# Посмотреть размер можно:;
a_centered.shape

(5, 2)

In [12]:
'''Задание 3
Найдите скалярное произведение столбцов массива 
a_centered. В результате должна получиться 
величина a_centered_sp. Затем поделите a_centered_sp 
на N-1, где N - число наблюдений.
''';

In [13]:
# скалярное произведение - построчно перемножить элементы и сложить:
# a[0]*b[0] + a[1]*b[1] ...
a_centered_sp = np.sum(a_centered[:,0] * a_centered[:,1])
a_centered_sp

8.0

In [14]:
# Наиболее правильно выбрать число N из 
# заданного ранее массива - обратиться
# к этому массиву по индексу (метод shape
# показывает количество строк)
N = a_centered.shape[0]
N

5

In [15]:
np.divide(a_centered_sp, N-1)

2.0

In [16]:
'''Задание 4**
Число, которое мы получили в конце задания 3 является 
ковариацией двух признаков, содержащихся в массиве “а”. 
В задании 3 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами 
величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив 
ковариацию еще одним способом - с помощью функции 
np.cov. В качестве аргумента m функция np.cov должна 
принимать транспонированный массив “a”. В получившейся 
ковариационной матрице (массив Numpy размером 2x2)
искомое значение ковариации будет равно элементу в 
строке с индексом 0 и столбце с индексом 1.
''';

In [17]:
a_centered_sp_np_cov = np.cov(a.T)
a_centered_sp_np_cov

array([[1. , 2. ],
       [2. , 4.3]])

## Работа с данными в Pandas

In [18]:
'''Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd.
Создайте датафрейм authors со столбцами author_id и 
author_name, в которых соответственно содержатся 
данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, 
book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 
'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].
''';

In [19]:
import pandas as pd

In [20]:
authors = pd.DataFrame({'author_id': [1, 2, 3],
                        'author_name': ['Тургенев','Чехов','Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [21]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо',
                                   'Толстый и тонкий', 'Дама с собачкой',
                                   'Гроза', 'Таланты и поклонники'],
                   'price': [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [22]:
'''Задание 2
Получите датафрейм authors_price, соединив 
датафреймы authors и books по полю author_id.
''';

In [23]:
authors_price = pd.merge(authors, book, on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [24]:
'''Задание 3
Создайте датафрейм top5, в котором содержатся 
строки из authors_price с пятью самыми дорогими книгами.
''';

In [30]:
# sort_values - функция для сортировки
# ascending - восходящий. Это и обзначает
top5 = authors_price.sort_values('price', ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [31]:
'''Задание 4
Создайте датафрейм authors_stat на основе информации 
из authors_price. В датафрейме authors_stat должны 
быть четыре столбца:

author_name, min_price, max_price и mean_price,

в которых должны содержаться соответственно имя автора,
минимальная, максимальная и средняя цена на 
книги этого автора.
''';

In [ ]:
authors_stat = pd.authors_price('author_name', 'min_price', 'max_price', 'mean_price')
authors_stat
# надо серъёзней подумать